export const dummyProductList = [
    {
        childProductId: 155,
        parentProductName: "페이즈2 흰강낭콩추출물",
        parentProductBrand: "나우푸드",
        imagePath: "https://healthfriend.s3.ap-northeast-2.amazonaws.com/20201211_518.jpg",
        price: "11,020원",
        reviewAverageRating: "0.00",
        flavorStr: "임시 맛",
        unit: "1개",
        capacityStr: "2kg",
        reviewTotalCount: 0,
        isFavorite: true,
        favoriteTotalCount: 132,
        summary: [
            {
                key: "맛",
                value: "매우 좋은 편이에요",
            },
            {
                key: "부작용",
                value: "거의 없는 편이에요",
            },
            {
                key: "재구매 의사",
                value: "높은 편이에요",
            },
        ]
    },
    {
        childProductId: 156,
        parentProductName: "페이즈2 흰강낭콩추출물 (식물성 캡슐)",
        parentProductBrand: "헬시오리진스",
        imagePath: "https://healthfriend.s3.ap-northeast-2.amazonaws.com/20201104_863.jpg",
        price: "가격 없음",
        reviewAverageRating: "0.00",
        flavorStr: "임시 맛",
        unit: "1개",
        capacityStr: "2kg",
        reviewTotalCount: 0,
        isFavorite: true,
        favoriteTotalCount: 14,
        summary: [
            {
                key: "맛",
                value: "매우 좋은 편이에요",
            },
            {
                key: "부작용",
                value: "거의 없는 편이에요",
            },
            {
                key: "재구매 의사",
                value: "높은 편이에요",
            },
        ]
    },
    {
        childProductId: 158,
        parentProductName: "흰강낭콩추출물",
        parentProductBrand: "퓨처바이오틱스",
        imagePath: "https://healthfriend.s3.ap-northeast-2.amazonaws.com/20201104_244.jpg",
        price: "16,840원",
        reviewAverageRating: "0.00",
        flavorStr: "임시 맛",
        unit: "1개",
        capacityStr: "2kg",
        reviewTotalCount: 0,
        isFavorite: false,
        favoriteTotalCount: 263,
        summary: [
            {
                key: "맛",
                value: "매우 좋은 편이에요",
            },
            {
                key: "부작용",
                value: "거의 없는 편이에요",
            },
            {
                key: "재구매 의사",
                value: "높은 편이에요",
            },
        ]
    },
    {
        childProductId: 157,
        parentProductName: "페이즈2 흰강낭콩추출물",
        parentProductBrand: "네이쳐스 웨이",
        imagePath: "https://healthfriend.s3.ap-northeast-2.amazonaws.com/20201104_506.jpg",
        price: "14,680원",
        reviewAverageRating: "0.00",
        flavorStr: "임시 맛",
        unit: "1개",
        capacityStr: "2kg",
        reviewTotalCount: 0,
        isFavorite: false,
        favoriteTotalCount: 0,
    },
    {
        childProductId: 159,
        parentProductName: "페이즈2 흰강낭콩추출물 (식물성 캡슐)",
        parentProductBrand: "나트롤",
        imagePath: "https://healthfriend.s3.ap-northeast-2.amazonaws.com/20201104_939.jpg",
        price: "18,070원",
        reviewAverageRating: "0.00",
        flavorStr: "임시 맛",
        unit: "1개",
        capacityStr: "2kg",
        reviewTotalCount: 0,
        isFavorite: false,
        favoriteTotalCount: 0,
    },
    {
        childProductId: 155,
        parentProductName: "페이즈2 흰강낭콩추출물",
        parentProductBrand: "나우푸드",
        imagePath: "https://healthfriend.s3.ap-northeast-2.amazonaws.com/20201211_518.jpg",
        price: "11,020원",
        reviewAverageRating: "0.00",
        flavorStr: "임시 맛",
        unit: "1개",
        capacityStr: "2kg",
        reviewTotalCount: 0,
        isFavorite: false,
        favoriteTotalCount: 0,
    },
    {
        childProductId: 156,
        parentProductName: "페이즈2 흰강낭콩추출물 (식물성 캡슐)",
        parentProductBrand: "헬시오리진스",
        imagePath: "https://healthfriend.s3.ap-northeast-2.amazonaws.com/20201104_863.jpg",
        price: "가격 없음",
        reviewAverageRating: "0.00",
        flavorStr: "임시 맛",
        unit: "1개",
        capacityStr: "2kg",
        reviewTotalCount: 0,
        isFavorite: false,
        favoriteTotalCount: 0,
    },
    {
        childProductId: 158,
        parentProductName: "흰강낭콩추출물",
        parentProductBrand: "퓨처바이오틱스",
        imagePath: "https://healthfriend.s3.ap-northeast-2.amazonaws.com/20201104_244.jpg",
        price: "16,840원",
        reviewAverageRating: "0.00",
        flavorStr: "임시 맛",
        unit: "1개",
        capacityStr: "2kg",
        reviewTotalCount: 0,
        isFavorite: false,
        favoriteTotalCount: 0,
    },
    {
        childProductId: 157,
        parentProductName: "페이즈2 흰강낭콩추출물",
        parentProductBrand: "네이쳐스 웨이",
        imagePath: "https://healthfriend.s3.ap-northeast-2.amazonaws.com/20201104_506.jpg",
        price: "14,680원",
        reviewAverageRating: "0.00",
        flavorStr: "임시 맛",
        unit: "1개",
        capacityStr: "2kg",
        reviewTotalCount: 0,
        isFavorite: false,
        favoriteTotalCount: 0,
    },
    {
        childProductId: 159,
        parentProductName: "페이즈2 흰강낭콩추출물 (식물성 캡슐)",
        parentProductBrand: "나트롤",
        imagePath: "https://healthfriend.s3.ap-northeast-2.amazonaws.com/20201104_939.jpg",
        price: "18,070원",
        reviewAverageRating: "0.00",
        reviewTotalCount: 0,
        isFavorite: false,
        favoriteTotalCount: 0,
    },
    {
        childProductId: 155,
        parentProductName: "페이즈2 흰강낭콩추출물",
        parentProductBrand: "나우푸드",
        imagePath: "https://healthfriend.s3.ap-northeast-2.amazonaws.com/20201211_518.jpg",
        price: "11,020원",
        reviewAverageRating: "0.00",
        flavorStr: "임시 맛",
        unit: "1개",
        capacityStr: "2kg",
        reviewTotalCount: 0,
        isFavorite: true,
        favoriteTotalCount: 132,
        summary: [
            {
                key: "맛",
                value: "매우 좋은 편이에요",
            },
            {
                key: "부작용",
                value: "거의 없는 편이에요",
            },
            {
                key: "재구매 의사",
                value: "높은 편이에요",
            },
        ]
    },
    {
        childProductId: 156,
        parentProductName: "페이즈2 흰강낭콩추출물 (식물성 캡슐)",
        parentProductBrand: "헬시오리진스",
        imagePath: "https://healthfriend.s3.ap-northeast-2.amazonaws.com/20201104_863.jpg",
        price: "가격 없음",
        reviewAverageRating: "0.00",
        flavorStr: "임시 맛",
        unit: "1개",
        capacityStr: "2kg",
        reviewTotalCount: 0,
        isFavorite: true,
        favoriteTotalCount: 14,
        summary: [
            {
                key: "맛",
                value: "매우 좋은 편이에요",
            },
            {
                key: "부작용",
                value: "거의 없는 편이에요",
            },
            {
                key: "재구매 의사",
                value: "높은 편이에요",
            },
        ]
    },
    {
        childProductId: 158,
        parentProductName: "흰강낭콩추출물",
        parentProductBrand: "퓨처바이오틱스",
        imagePath: "https://healthfriend.s3.ap-northeast-2.amazonaws.com/20201104_244.jpg",
        price: "16,840원",
        reviewAverageRating: "0.00",
        flavorStr: "임시 맛",
        unit: "1개",
        capacityStr: "2kg",
        reviewTotalCount: 0,
        isFavorite: false,
        favoriteTotalCount: 263,
        summary: [
            {
                key: "맛",
                value: "매우 좋은 편이에요",
            },
            {
                key: "부작용",
                value: "거의 없는 편이에요",
            },
            {
                key: "재구매 의사",
                value: "높은 편이에요",
            },
        ]
    },
    {
        childProductId: 157,
        parentProductName: "페이즈2 흰강낭콩추출물",
        parentProductBrand: "네이쳐스 웨이",
        imagePath: "https://healthfriend.s3.ap-northeast-2.amazonaws.com/20201104_506.jpg",
        price: "14,680원",
        reviewAverageRating: "0.00",
        flavorStr: "임시 맛",
        unit: "1개",
        capacityStr: "2kg",
        reviewTotalCount: 0,
        isFavorite: false,
        favoriteTotalCount: 0,
    },
    {
        childProductId: 159,
        parentProductName: "페이즈2 흰강낭콩추출물 (식물성 캡슐)",
        parentProductBrand: "나트롤",
        imagePath: "https://healthfriend.s3.ap-northeast-2.amazonaws.com/20201104_939.jpg",
        price: "18,070원",
        reviewAverageRating: "0.00",
        flavorStr: "임시 맛",
        unit: "1개",
        capacityStr: "2kg",
        reviewTotalCount: 0,
        isFavorite: false,
        favoriteTotalCount: 0,
    },
    {
        childProductId: 155,
        parentProductName: "페이즈2 흰강낭콩추출물",
        parentProductBrand: "나우푸드",
        imagePath: "https://healthfriend.s3.ap-northeast-2.amazonaws.com/20201211_518.jpg",
        price: "11,020원",
        reviewAverageRating: "0.00",
        flavorStr: "임시 맛",
        unit: "1개",
        capacityStr: "2kg",
        reviewTotalCount: 0,
        isFavorite: false,
        favoriteTotalCount: 0,
    },
    {
        childProductId: 156,
        parentProductName: "페이즈2 흰강낭콩추출물 (식물성 캡슐)",
        parentProductBrand: "헬시오리진스",
        imagePath: "https://healthfriend.s3.ap-northeast-2.amazonaws.com/20201104_863.jpg",
        price: "가격 없음",
        reviewAverageRating: "0.00",
        flavorStr: "임시 맛",
        unit: "1개",
        capacityStr: "2kg",
        reviewTotalCount: 0,
        isFavorite: false,
        favoriteTotalCount: 0,
    },
    {
        childProductId: 158,
        parentProductName: "흰강낭콩추출물",
        parentProductBrand: "퓨처바이오틱스",
        imagePath: "https://healthfriend.s3.ap-northeast-2.amazonaws.com/20201104_244.jpg",
        price: "16,840원",
        reviewAverageRating: "0.00",
        flavorStr: "임시 맛",
        unit: "1개",
        capacityStr: "2kg",
        reviewTotalCount: 0,
        isFavorite: false,
        favoriteTotalCount: 0,
    },
    {
        childProductId: 157,
        parentProductName: "페이즈2 흰강낭콩추출물",
        parentProductBrand: "네이쳐스 웨이",
        imagePath: "https://healthfriend.s3.ap-northeast-2.amazonaws.com/20201104_506.jpg",
        price: "14,680원",
        reviewAverageRating: "0.00",
        flavorStr: "임시 맛",
        unit: "1개",
        capacityStr: "2kg",
        reviewTotalCount: 0,
        isFavorite: false,
        favoriteTotalCount: 0,
    },
    {
        childProductId: 159,
        parentProductName: "페이즈2 흰강낭콩추출물 (식물성 캡슐)",
        parentProductBrand: "나트롤",
        imagePath: "https://healthfriend.s3.ap-northeast-2.amazonaws.com/20201104_939.jpg",
        price: "18,070원",
        reviewAverageRating: "0.00",
        reviewTotalCount: 0,
        isFavorite: false,
        favoriteTotalCount: 0,
    },
    {
        childProductId: 155,
        parentProductName: "페이즈2 흰강낭콩추출물",
        parentProductBrand: "나우푸드",
        imagePath: "https://healthfriend.s3.ap-northeast-2.amazonaws.com/20201211_518.jpg",
        price: "11,020원",
        reviewAverageRating: "0.00",
        flavorStr: "임시 맛",
        unit: "1개",
        capacityStr: "2kg",
        reviewTotalCount: 0,
        isFavorite: true,
        favoriteTotalCount: 132,
        summary: [
            {
                key: "맛",
                value: "매우 좋은 편이에요",
            },
            {
                key: "부작용",
                value: "거의 없는 편이에요",
            },
            {
                key: "재구매 의사",
                value: "높은 편이에요",
            },
        ]
    },
    {
        childProductId: 156,
        parentProductName: "페이즈2 흰강낭콩추출물 (식물성 캡슐)",
        parentProductBrand: "헬시오리진스",
        imagePath: "https://healthfriend.s3.ap-northeast-2.amazonaws.com/20201104_863.jpg",
        price: "가격 없음",
        reviewAverageRating: "0.00",
        flavorStr: "임시 맛",
        unit: "1개",
        capacityStr: "2kg",
        reviewTotalCount: 0,
        isFavorite: true,
        favoriteTotalCount: 14,
        summary: [
            {
                key: "맛",
                value: "매우 좋은 편이에요",
            },
            {
                key: "부작용",
                value: "거의 없는 편이에요",
            },
            {
                key: "재구매 의사",
                value: "높은 편이에요",
            },
        ]
    },
    {
        childProductId: 158,
        parentProductName: "흰강낭콩추출물",
        parentProductBrand: "퓨처바이오틱스",
        imagePath: "https://healthfriend.s3.ap-northeast-2.amazonaws.com/20201104_244.jpg",
        price: "16,840원",
        reviewAverageRating: "0.00",
        flavorStr: "임시 맛",
        unit: "1개",
        capacityStr: "2kg",
        reviewTotalCount: 0,
        isFavorite: false,
        favoriteTotalCount: 263,
        summary: [
            {
                key: "맛",
                value: "매우 좋은 편이에요",
            },
            {
                key: "부작용",
                value: "거의 없는 편이에요",
            },
            {
                key: "재구매 의사",
                value: "높은 편이에요",
            },
        ]
    },
    {
        childProductId: 157,
        parentProductName: "페이즈2 흰강낭콩추출물",
        parentProductBrand: "네이쳐스 웨이",
        imagePath: "https://healthfriend.s3.ap-northeast-2.amazonaws.com/20201104_506.jpg",
        price: "14,680원",
        reviewAverageRating: "0.00",
        flavorStr: "임시 맛",
        unit: "1개",
        capacityStr: "2kg",
        reviewTotalCount: 0,
        isFavorite: false,
        favoriteTotalCount: 0,
    },
    {
        childProductId: 159,
        parentProductName: "페이즈2 흰강낭콩추출물 (식물성 캡슐)",
        parentProductBrand: "나트롤",
        imagePath: "https://healthfriend.s3.ap-northeast-2.amazonaws.com/20201104_939.jpg",
        price: "18,070원",
        reviewAverageRating: "0.00",
        flavorStr: "임시 맛",
        unit: "1개",
        capacityStr: "2kg",
        reviewTotalCount: 0,
        isFavorite: false,
        favoriteTotalCount: 0,
    },
    {
        childProductId: 155,
        parentProductName: "페이즈2 흰강낭콩추출물",
        parentProductBrand: "나우푸드",
        imagePath: "https://healthfriend.s3.ap-northeast-2.amazonaws.com/20201211_518.jpg",
        price: "11,020원",
        reviewAverageRating: "0.00",
        flavorStr: "임시 맛",
        unit: "1개",
        capacityStr: "2kg",
        reviewTotalCount: 0,
        isFavorite: false,
        favoriteTotalCount: 0,
    },
    {
        childProductId: 156,
        parentProductName: "페이즈2 흰강낭콩추출물 (식물성 캡슐)",
        parentProductBrand: "헬시오리진스",
        imagePath: "https://healthfriend.s3.ap-northeast-2.amazonaws.com/20201104_863.jpg",
        price: "가격 없음",
        reviewAverageRating: "0.00",
        flavorStr: "임시 맛",
        unit: "1개",
        capacityStr: "2kg",
        reviewTotalCount: 0,
        isFavorite: false,
        favoriteTotalCount: 0,
    },
    {
        childProductId: 158,
        parentProductName: "흰강낭콩추출물",
        parentProductBrand: "퓨처바이오틱스",
        imagePath: "https://healthfriend.s3.ap-northeast-2.amazonaws.com/20201104_244.jpg",
        price: "16,840원",
        reviewAverageRating: "0.00",
        flavorStr: "임시 맛",
        unit: "1개",
        capacityStr: "2kg",
        reviewTotalCount: 0,
        isFavorite: false,
        favoriteTotalCount: 0,
    },
    {
        childProductId: 157,
        parentProductName: "페이즈2 흰강낭콩추출물",
        parentProductBrand: "네이쳐스 웨이",
        imagePath: "https://healthfriend.s3.ap-northeast-2.amazonaws.com/20201104_506.jpg",
        price: "14,680원",
        reviewAverageRating: "0.00",
        flavorStr: "임시 맛",
        unit: "1개",
        capacityStr: "2kg",
        reviewTotalCount: 0,
        isFavorite: false,
        favoriteTotalCount: 0,
    },
    {
        childProductId: 159,
        parentProductName: "페이즈2 흰강낭콩추출물 (식물성 캡슐)",
        parentProductBrand: "나트롤",
        imagePath: "https://healthfriend.s3.ap-northeast-2.amazonaws.com/20201104_939.jpg",
        price: "18,070원",
        reviewAverageRating: "0.00",
        reviewTotalCount: 0,
        isFavorite: false,
        favoriteTotalCount: 0,
    },
    {
        childProductId: 155,
        parentProductName: "페이즈2 흰강낭콩추출물",
        parentProductBrand: "나우푸드",
        imagePath: "https://healthfriend.s3.ap-northeast-2.amazonaws.com/20201211_518.jpg",
        price: "11,020원",
        reviewAverageRating: "0.00",
        flavorStr: "임시 맛",
        unit: "1개",
        capacityStr: "2kg",
        reviewTotalCount: 0,
        isFavorite: true,
        favoriteTotalCount: 132,
        summary: [
            {
                key: "맛",
                value: "매우 좋은 편이에요",
            },
            {
                key: "부작용",
                value: "거의 없는 편이에요",
            },
            {
                key: "재구매 의사",
                value: "높은 편이에요",
            },
        ]
    },
    {
        childProductId: 156,
        parentProductName: "페이즈2 흰강낭콩추출물 (식물성 캡슐)",
        parentProductBrand: "헬시오리진스",
        imagePath: "https://healthfriend.s3.ap-northeast-2.amazonaws.com/20201104_863.jpg",
        price: "가격 없음",
        reviewAverageRating: "0.00",
        flavorStr: "임시 맛",
        unit: "1개",
        capacityStr: "2kg",
        reviewTotalCount: 0,
        isFavorite: true,
        favoriteTotalCount: 14,
        summary: [
            {
                key: "맛",
                value: "매우 좋은 편이에요",
            },
            {
                key: "부작용",
                value: "거의 없는 편이에요",
            },
            {
                key: "재구매 의사",
                value: "높은 편이에요",
            },
        ]
    },
    {
        childProductId: 158,
        parentProductName: "흰강낭콩추출물",
        parentProductBrand: "퓨처바이오틱스",
        imagePath: "https://healthfriend.s3.ap-northeast-2.amazonaws.com/20201104_244.jpg",
        price: "16,840원",
        reviewAverageRating: "0.00",
        flavorStr: "임시 맛",
        unit: "1개",
        capacityStr: "2kg",
        reviewTotalCount: 0,
        isFavorite: false,
        favoriteTotalCount: 263,
        summary: [
            {
                key: "맛",
                value: "매우 좋은 편이에요",
            },
            {
                key: "부작용",
                value: "거의 없는 편이에요",
            },
            {
                key: "재구매 의사",
                value: "높은 편이에요",
            },
        ]
    },
    {
        childProductId: 157,
        parentProductName: "페이즈2 흰강낭콩추출물",
        parentProductBrand: "네이쳐스 웨이",
        imagePath: "https://healthfriend.s3.ap-northeast-2.amazonaws.com/20201104_506.jpg",
        price: "14,680원",
        reviewAverageRating: "0.00",
        flavorStr: "임시 맛",
        unit: "1개",
        capacityStr: "2kg",
        reviewTotalCount: 0,
        isFavorite: false,
        favoriteTotalCount: 0,
    },
    {
        childProductId: 159,
        parentProductName: "페이즈2 흰강낭콩추출물 (식물성 캡슐)",
        parentProductBrand: "나트롤",
        imagePath: "https://healthfriend.s3.ap-northeast-2.amazonaws.com/20201104_939.jpg",
        price: "18,070원",
        reviewAverageRating: "0.00",
        flavorStr: "임시 맛",
        unit: "1개",
        capacityStr: "2kg",
        reviewTotalCount: 0,
        isFavorite: false,
        favoriteTotalCount: 0,
    },
    {
        childProductId: 155,
        parentProductName: "페이즈2 흰강낭콩추출물",
        parentProductBrand: "나우푸드",
        imagePath: "https://healthfriend.s3.ap-northeast-2.amazonaws.com/20201211_518.jpg",
        price: "11,020원",
        reviewAverageRating: "0.00",
        flavorStr: "임시 맛",
        unit: "1개",
        capacityStr: "2kg",
        reviewTotalCount: 0,
        isFavorite: false,
        favoriteTotalCount: 0,
    },
    {
        childProductId: 156,
        parentProductName: "페이즈2 흰강낭콩추출물 (식물성 캡슐)",
        parentProductBrand: "헬시오리진스",
        imagePath: "https://healthfriend.s3.ap-northeast-2.amazonaws.com/20201104_863.jpg",
        price: "가격 없음",
        reviewAverageRating: "0.00",
        flavorStr: "임시 맛",
        unit: "1개",
        capacityStr: "2kg",
        reviewTotalCount: 0,
        isFavorite: false,
        favoriteTotalCount: 0,
    },
    {
        childProductId: 158,
        parentProductName: "흰강낭콩추출물",
        parentProductBrand: "퓨처바이오틱스",
        imagePath: "https://healthfriend.s3.ap-northeast-2.amazonaws.com/20201104_244.jpg",
        price: "16,840원",
        reviewAverageRating: "0.00",
        flavorStr: "임시 맛",
        unit: "1개",
        capacityStr: "2kg",
        reviewTotalCount: 0,
        isFavorite: false,
        favoriteTotalCount: 0,
    },
    {
        childProductId: 157,
        parentProductName: "페이즈2 흰강낭콩추출물",
        parentProductBrand: "네이쳐스 웨이",
        imagePath: "https://healthfriend.s3.ap-northeast-2.amazonaws.com/20201104_506.jpg",
        price: "14,680원",
        reviewAverageRating: "0.00",
        flavorStr: "임시 맛",
        unit: "1개",
        capacityStr: "2kg",
        reviewTotalCount: 0,
        isFavorite: false,
        favoriteTotalCount: 0,
    },
    {
        childProductId: 159,
        parentProductName: "페이즈2 흰강낭콩추출물 (식물성 캡슐)",
        parentProductBrand: "나트롤",
        imagePath: "https://healthfriend.s3.ap-northeast-2.amazonaws.com/20201104_939.jpg",
        price: "18,070원",
        reviewAverageRating: "0.00",
        reviewTotalCount: 0,
        isFavorite: false,
        favoriteTotalCount: 0,
    },
]

export const dummyRankingProductList = [
    {
        childProductId: 167,
        parentProductBrand: "머슬팜",
        parentProductName: "컴뱃 100% 아이솔레이트",
        imagePath: "https://healthfriend.s3.ap-northeast-2.amazonaws.com/20201106_823.jpg",
        reviewAverageRating: "5.00",
        reviewTotalCount: 10,
        price: "0원",
        flavorStr: "임시 맛",
        unit: "1개",
        capacityStr: "2.27kg"
    },
    {
        childProductId: 218,
        parentProductBrand: "BSN",
        parentProductName: "신타6",
        imagePath: "https://healthfriend.s3.ap-northeast-2.amazonaws.com/20201125_218.jpg",
        reviewAverageRating: "5.00",
        reviewTotalCount: 8,
        price: "53,100원",
        flavorStr: "임시 맛",
        unit: "1개",
        capacityStr: "2.27kg"
    },
    {
        childProductId: 213,
        parentProductBrand: "BSN",
        parentProductName: "신타6 아이솔레이트",
        imagePath: "https://healthfriend.s3.ap-northeast-2.amazonaws.com/20201124_400.jpg",
        reviewAverageRating: "4.80",
        reviewTotalCount: 5,
        price: "62,380원",
        flavorStr: "임시 맛",
        unit: "1개",
        capacityStr: "1.82kg"
    },
    {
        childProductId: 223,
        parentProductBrand: "마이프로틴",
        parentProductName: "임팩트 웨이 프로틴",
        imagePath: "https://healthfriend.s3.ap-northeast-2.amazonaws.com/20201203_979.jpg",
        reviewAverageRating: "3.97",
        reviewTotalCount: 29,
        price: "0원",
        flavorStr: "임시 맛",
        unit: "1개",
        capacityStr: "2.5kg"
    },
    {
        childProductId: 187,
        parentProductBrand: "옵티멈 뉴트리션",
        parentProductName: "플래티넘 하이드로 웨이",
        imagePath: "https://healthfriend.s3.ap-northeast-2.amazonaws.com/20201117_221.jpg",
        reviewAverageRating: "4.71",
        reviewTotalCount: 7,
        price: "74,160원",
        flavorStr: "임시 맛",
        unit: "1개",
        capacityStr: "1.59kg"
    },
    {
        childProductId: 331,
        parentProductBrand: "셀렉스",
        parentProductName: "스포츠 웨이 프로틴 드링크",
        imagePath: "https://healthfriend.s3.ap-northeast-2.amazonaws.com/20210107_774.jpg",
        reviewAverageRating: "4.57",
        reviewTotalCount: 7,
        price: "가격 없음",
        flavorStr: "임시 맛",
        unit: "1개",
        capacityStr: "330ml"
    },
    {
        childProductId: 196,
        parentProductBrand: "칼로바이",
        parentProductName: "퍼펙트 파워쉐이크(RTD)",
        imagePath: "https://healthfriend.s3.ap-northeast-2.amazonaws.com/20201119_541.jpg",
        reviewAverageRating: "4.20",
        reviewTotalCount: 5,
        price: "24,140원",
        flavorStr: "임시 맛",
        unit: "1개",
        capacityStr: "10팩"
    },
    {
        childProductId: 172,
        parentProductBrand: "나우스포츠",
        parentProductName: "웨이 프로틴 아이솔레이트",
        imagePath: "https://healthfriend.s3.ap-northeast-2.amazonaws.com/20201111_563.jpg",
        reviewAverageRating: "5.00",
        reviewTotalCount: 1,
        price: "88,590원",
        flavorStr: "임시 맛",
        unit: "1개",
        capacityStr: "2.27kg"
    },
]

export const dummyHighViewProductList = [
    {
        childProductId: 14,
        parentProductBrand: "엠알엠 뉴트리션",
        parentProductName: "리로드 BCAA+G",
        imagePath: "https://healthfriend.s3.ap-northeast-2.amazonaws.com/20201022_151.jpg",
        reviewAverageRating: "5.00",
        reviewTotalCount: 1,
        price: "17,410원",
        flavorStr: "임시 맛",
        unit: "1개",
        capacityStr: "330g"
    },
    {
        childProductId: 19,
        parentProductBrand: "나우푸드",
        parentProductName: "L-글루타민 (캡슐)",
        imagePath: "https://healthfriend.s3.ap-northeast-2.amazonaws.com/20201027_392.jpg",
        reviewAverageRating: "5.00",
        reviewTotalCount: 1,
        price: "10,060원",
        flavorStr: "임시 맛",
        unit: "1개",
        capacityStr: "120캡슐"
    },
    {
        childProductId: 32,
        parentProductBrand: "캘리포니아 골드 뉴트리션",
        parentProductName: "L-글루타민",
        imagePath: "https://healthfriend.s3.ap-northeast-2.amazonaws.com/20201028_143.jpg",
        reviewAverageRating: "5.00",
        reviewTotalCount: 1,
        price: "19,366원",
        flavorStr: "임시 맛",
        unit: "1개",
        capacityStr: "454g"
    },
    {
        childProductId: 42,
        parentProductBrand: "게토레이",
        parentProductName: "게토레이 썰스트 퀜처 파우더",
        imagePath: "https://healthfriend.s3.ap-northeast-2.amazonaws.com/20201028_44.jpg",
        reviewAverageRating: "5.00",
        reviewTotalCount: 1,
        price: "가격 없음",
        flavorStr: "임시 맛",
        unit: "1개",
        capacityStr: "521g"
    },
    {
        childProductId: 43,
        parentProductBrand: "나우스포츠",
        parentProductName: "크레아틴 모노하이드레이트",
        imagePath: "https://healthfriend.s3.ap-northeast-2.amazonaws.com/20201028_367.jpg",
        reviewAverageRating: "5.00",
        reviewTotalCount: 1,
        price: "9,290원",
        flavorStr: "임시 맛",
        unit: "1개",
        capacityStr: "227g"
    },
    {
        childProductId: 44,
        parentProductBrand: "포카리스웨트",
        parentProductName: "포카리스웨트 분말",
        imagePath: "https://healthfriend.s3.ap-northeast-2.amazonaws.com/20201028_969.jpg",
        reviewAverageRating: "5.00",
        reviewTotalCount: 2,
        price: "7,400원",
        flavorStr: "임시 맛",
        unit: "1개",
        capacityStr: "74g",
    },
    {
        childProductId: 48,
        parentProductBrand: "SAN",
        parentProductName: "퍼포먼스 크레아틴",
        imagePath: "https://healthfriend.s3.ap-northeast-2.amazonaws.com/20201028_568.jpg",
        reviewAverageRating: "4.50",
        reviewTotalCount: 2,
        price: "26,930원",
        flavorStr: "임시 맛",
        unit: "1개",
        capacityStr: "300g"
    },
]

export const dummyNewProductList = [
    {
        childProductId: 293,
        parentProductBrand: "닥터유",
        parentProductName: "단백질바",
        imagePath: "https://healthfriend.s3.ap-northeast-2.amazonaws.com/20201209_75.jpg",
        reviewAverageRating: "4.50",
        reviewTotalCount: 18,
        price: "9,900원",
        flavorStr: "임시 맛",
        unit: "1개",
        capacityStr: "34g",
        summary: [
            {
                key: "맛",
                value: "매우 좋은 편이에요",
            },
            {
                key: "부작용",
                value: "거의 없는 편이에요",
            },
            {
                key: "재구매 의사",
                value: "높은 편이에요",
            },
        ],
    },
    {
        childProductId: 306,
        parentProductBrand: "마이프로틴",
        parentProductName: "6 레이어 프로틴바(육겹바)",
        imagePath: "https://healthfriend.s3.ap-northeast-2.amazonaws.com/20201210_604.jpg",
        reviewAverageRating: "4.40",
        reviewTotalCount: 5,
        price: "49,900원",
        flavorStr: "임시 맛",
        unit: "1개",
        capacityStr: "60g",
        summary: [
            {
                key: "맛",
                value: "매우 좋은 편이에요",
            },
            {
                key: "부작용",
                value: "거의 없는 편이에요",
            },
            {
                key: "재구매 의사",
                value: "높은 편이에요",
            },
        ],
    },
    {
        childProductId: 286,
        parentProductBrand: "BSN",
        parentProductName: "프로틴 크리스프바",
        imagePath: "https://healthfriend.s3.ap-northeast-2.amazonaws.com/20201208_897.jpg-1",
        reviewAverageRating: "5.00",
        reviewTotalCount: 1,
        price: "0원",
        flavorStr: "임시 맛",
        unit: "1개",
        capacityStr: "57g",
        summary: [
            {
                key: "맛",
                value: "매우 좋은 편이에요",
            },
            {
                key: "부작용",
                value: "거의 없는 편이에요",
            },
            {
                key: "재구매 의사",
                value: "높은 편이에요",
            },
        ],
    },
    {
        childProductId: 287,
        parentProductBrand: "캘리포니아 골드 뉴트리션",
        parentProductName: "푸드바",
        imagePath: "https://healthfriend.s3.ap-northeast-2.amazonaws.com/20201208_197.jpg",
        reviewAverageRating: "5.00",
        reviewTotalCount: 4,
        price: "14,524원",
        flavorStr: "임시 맛",
        unit: "1개",
        capacityStr: "40g"
    },
    {
        childProductId: 299,
        parentProductBrand: "퀘스트 뉴트리션",
        parentProductName: "프로틴 쿠키",
        imagePath: "https://healthfriend.s3.ap-northeast-2.amazonaws.com/20201210_186.jpg",
        reviewAverageRating: "5.00",
        reviewTotalCount: 3,
        price: "22,510원",
        flavorStr: "임시 맛",
        unit: "1개",
        capacityStr: "59g"
    },
    {
        childProductId: 300,
        parentProductBrand: "다신",
        parentProductName: "통밀당 단백칩",
        imagePath: "https://healthfriend.s3.ap-northeast-2.amazonaws.com/20201209_444.jpg",
        reviewAverageRating: "5.00",
        reviewTotalCount: 3,
        price: "2,500원",
        flavorStr: "임시 맛",
        unit: "1개",
        capacityStr: "45g"
    },
    {
        childProductId: 307,
        parentProductBrand: "마이프로틴",
        parentProductName: "프로틴 와퍼",
        imagePath: "https://healthfriend.s3.ap-northeast-2.amazonaws.com/20201210_286.jpg",
        reviewAverageRating: "4.67",
        reviewTotalCount: 3,
        price: "38,900원",
        flavorStr: "임시 맛",
        unit: "1개",
        capacityStr: "41.9g"
    },
    {
        childProductId: 285,
        parentProductBrand: "머슬팜",
        parentProductName: "컴뱃 크런치바",
        imagePath: "https://healthfriend.s3.ap-northeast-2.amazonaws.com/20201207_352.jpg",
        reviewAverageRating: "4.50",
        reviewTotalCount: 2,
        price: "25,100원",
        flavorStr: "임시 맛",
        unit: "1개",
        capacityStr: "63g"
    },
    {
        childProductId: 308,
        parentProductBrand: "마이프로틴",
        parentProductName: "프로틴 브라우니",
        imagePath: "https://healthfriend.s3.ap-northeast-2.amazonaws.com/20201224_787.jpg",
        reviewAverageRating: "4.00",
        reviewTotalCount: 1,
        price: "32,900원",
        flavorStr: "임시 맛",
        unit: "1개",
        capacityStr: "75g"
    },
]

export const dummyProductCategoryList = [
    {
        id: 1,
        name: "전체",
        childList: [],
    },
    {
        id: 2,
        name: "닭가슴살",
        childList: [
            {
                name: "전체",
                imgPath: "https://m.ocook.co.kr/web/product/big/202111/5fdf1a569df8c13742a11db9b16813a0.jpg",
            },
            {
                name: "스팀",
                imgPath: "http://th3.tmon.kr/thumbs/image/d4e/789/7c4/4eabdc023_700x700_95_FIT.jpg",
            },
            {
                name: "소프트",
                imgPath: "https://www.goobnemall.com/static-root/prdct/2021/05/28/d2be9595ca6242e893123d7291720034.jpg",
            },
            {
                name: "스테이크",
                imgPath: "https://onetopreview.net/wp-content/uploads/2022/01/%EB%8B%AD%EA%B0%80%EC%8A%B4%EC%82%B4-%EC%B6%94%EC%B2%9C-944x584.jpg",
            },
            {
                name: "소스닭가슴살",
                imgPath: "http://barudak.co.kr/web/product/tiny/202102/bd1b4cb10c81377ecf4c9eb5c0019ea3.jpg",
            },
            {
                name: "슬라이스",
                imgPath: "http://th3.tmon.kr/thumbs/image/d4e/789/7c4/4eabdc023_700x700_95_FIT.jpg",
            },
            {
                name: "볼ㆍ큐브",
                imgPath: "https://www.goobnemall.com/static-root/prdct/2021/05/28/d2be9595ca6242e893123d7291720034.jpg",
            },
            {
                name: "훈제",
                imgPath: "https://onetopreview.net/wp-content/uploads/2022/01/%EB%8B%AD%EA%B0%80%EC%8A%B4%EC%82%B4-%EC%B6%94%EC%B2%9C-944x584.jpg",
            },
            {
                name: "저염",
                imgPath: "http://barudak.co.kr/web/product/tiny/202102/bd1b4cb10c81377ecf4c9eb5c0019ea3.jpg",
            },
            {
                name: "소시지",
                imgPath: "http://th3.tmon.kr/thumbs/image/d4e/789/7c4/4eabdc023_700x700_95_FIT.jpg",
            },
        ],
    },
    {
        id: 3,
        name: "도시락·볶음밥",
        childList: [
            {
                name: "전체",
                imgPath: "https://m.nongmin.com/upload/news/2017/20170513193258/20170513193258.jpg",
            },
            {
                name: "냠냠이21",
                imgPath: "http://th3.tmon.kr/thumbs/image/d4e/789/7c4/4eabdc023_700x700_95_FIT.jpg",
            },
            {
                name: "냠냠이22",
                imgPath: "http://barudak.co.kr/web/product/tiny/202102/bd1b4cb10c81377ecf4c9eb5c0019ea3.jpg",
            },
            {
                name: "냠냠이23",
                imgPath: "https://www.goobnemall.com/static-root/prdct/2021/05/28/d2be9595ca6242e893123d7291720034.jpg",
            },
        ],
    },
    {
        id: 4,
        name: "즉석 간편식",
        childList: [
            {
                name: "전체",
                imgPath: "https://vegefeed.wisacdn.com/_data/product/goods/20/11/48/1000000178//1000000178_main_057.png",
            },
            {
                name: "핫도그·핫바",
                imgPath: "http://img.wemep.co.kr/deal/2/588/3815882/974f4bce34e9441fb0aa1c9ddffa9ebdf5a0fa00.jpg",
            },
            {
                name: "만두·브리또",
                imgPath: "https://data.0app0.com/diet/shop/goods/20210527/20210527144814_3522992584.jpg",
            },
        ],
    },
    {
        id: 5,
        name: "단백질 보충제",
        childList: [
            {
                name: "전체",
                imgPath: "http://image.auction.co.kr/itemimage/20/11/93/2011939f06.jpg",
            },
            {
                name: "유청 단백질",
                imgPath: "https://mdtoday.co.kr/news/data/20211209/p1065577997365627_534_thum.jpg",
            },
            {
                name: "식물성 단백질",
                imgPath: "https://www.rainbowextract.com/wp-content/uploads/2021/12/Plant-protain-1-300x225.jpg",
            },
            {
                name: "산양유 단백질",
                imgPath: "https://img.danawa.com/prod_img/500000/120/559/img/16559120_1.jpg",
            },
        ],
    },
    {
        id: 6,
        name: "프로틴 음료",
        childList: [],
    },
    {
        id: 7,
        name: "프로틴 간식",
        childList: [
            {
                name: "전체",
                imgPath: "http://image.auction.co.kr/itemimage/20/11/93/2011939f06.jpg",
            },
            {
                name: "프로틴 바",
                imgPath: "https://itembbal.com/wp-content/uploads/2021/07/%E1%84%91%E1%85%B3%E1%84%85%E1%85%A9%E1%84%90%E1%85%B5%E1%86%AB%E1%84%87%E1%85%A1.png",
            },
            {
                name: "과자·쿠키",
                imgPath: "https://mp-seoul-image-production-s3.mangoplate.com/885345_1608637422971611.jpg",
            },
        ],
    },
    {
        id: 8,
        name: "베이커리",
        childList: [],
    },
    {
        id: 9,
        name: "샐러드",
        childList: [],
    },
]

export const dummyMagazineResultList = [
    {
        magazineId: 1,
        title: "단백질과 통풍",
        subTitle: "",
        type: "단백과사전",
        imagePath: "https://user-images.githubusercontent.com/46476398/177967097-b35bd274-58f7-46b1-9c06-bc6e9e05179f.png",
        content: "",
        createdAt: "22.07.14",
        viewCnt: 2212,
        favoriteTotalCount: 123,
    },
    {
        magazineId: 2,
        title: "단백질과 통풍",
        subTitle: "(feat. 적용방법, 혜택)",
        type: "단백종원",
        imagePath: "https://user-images.githubusercontent.com/46476398/177967137-d34821b0-8474-46bf-bf1a-bcc7bc84ef87.png",
        content: "",
        createdAt: "22.07.14",
        viewCnt: 2312,
        favoriteTotalCount: 123,
    },
    {
        magazineId: 3,
        title: "음식별 단백질 함량",
        subTitle: "(feat. 날달걀 vs 삶은 닭걀)",
        type: "단백과사전",
        imagePath: "https://user-images.githubusercontent.com/46476398/177967141-80a22d1e-c2fa-42cb-a988-1c1efdb14959.png",
        content: "",
        createdAt: "22.07.14",
        viewCnt: 1012,
        favoriteTotalCount: 123,
    },
    {
        magazineId: 4,
        title: "닭가슴살 선택 방법",
        subTitle: "",
        type: "선택 가이드",
        imagePath: "https://user-images.githubusercontent.com/46476398/177967147-2d9b7077-a744-4d37-8526-52f2b7689d72.png",
        content: "",
        createdAt: "22.07.14",
        viewCnt: 2052,
        favoriteTotalCount: 123,
    },
    {
        magazineId: 5,
        title: "하루에 단백질은 얼마나?",
        subTitle: "",
        type: "단백과사전",
        imagePath: "https://user-images.githubusercontent.com/46476398/177967152-5c9032d7-8f01-42a3-a714-1a0a742fa181.png",
        content: "",
        createdAt: "22.07.14",
        viewCnt: 2014,
        favoriteTotalCount: 123,
    },
    {
        magazineId: 11,
        title: "단백질과 통풍",
        subTitle: "",
        type: "단백과사전",
        imagePath: "https://user-images.githubusercontent.com/46476398/177967097-b35bd274-58f7-46b1-9c06-bc6e9e05179f.png",
        content: "",
        createdAt: "22.07.14",
        viewCnt: 2212,
        favoriteTotalCount: 123,
    },
    {
        magazineId: 12,
        title: "단백질과 통풍",
        subTitle: "(feat. 적용방법, 혜택)",
        type: "단백종원",
        imagePath: "https://user-images.githubusercontent.com/46476398/177967137-d34821b0-8474-46bf-bf1a-bcc7bc84ef87.png",
        content: "",
        createdAt: "22.07.14",
        viewCnt: 2312,
        favoriteTotalCount: 123,
    },
    {
        magazineId: 13,
        title: "음식별 단백질 함량",
        subTitle: "(feat. 날달걀 vs 삶은 닭걀)",
        type: "단백과사전",
        imagePath: "https://user-images.githubusercontent.com/46476398/177967141-80a22d1e-c2fa-42cb-a988-1c1efdb14959.png",
        content: "",
        createdAt: "22.07.14",
        viewCnt: 1012,
        favoriteTotalCount: 123,
    },
    {
        magazineId: 14,
        title: "닭가슴살 선택 방법",
        subTitle: "",
        type: "선택 가이드",
        imagePath: "https://user-images.githubusercontent.com/46476398/177967147-2d9b7077-a744-4d37-8526-52f2b7689d72.png",
        content: "",
        createdAt: "22.07.14",
        viewCnt: 2052,
        favoriteTotalCount: 123,
    },
    {
        magazineId: 15,
        title: "하루에 단백질은 얼마나?",
        subTitle: "",
        type: "단백과사전",
        imagePath: "https://user-images.githubusercontent.com/46476398/177967152-5c9032d7-8f01-42a3-a714-1a0a742fa181.png",
        content: "",
        createdAt: "22.07.14",
        viewCnt: 2014,
        favoriteTotalCount: 123,
    },
]

export const dummyEventResultList = [
    {
        eventId: 1,
        title: "교촌 닭가슴살·볶음밥 최대 61% 할인",
        subTitle: "",
        type: "할인 이벤트",
        imagePath: "https://user-images.githubusercontent.com/46476398/177965223-55ee573a-7fff-4af8-97bd-529f545918ea.png",
        content: "",
        deadline: "22.07.14",
        status: "종료",
    },
    {
        eventId: 2,
        title: "랭킹닭컴 X KB국민카드, 결재시 20% 할인",
        subTitle: "",
        type: "할인 이벤트",
        imagePath: "https://user-images.githubusercontent.com/46476398/177965235-8d8dfec1-97c5-4497-b4df-e50229098513.png",
        content: "",
        deadline: "22.07.14",
        status: "진행중",
    },
    {
        eventId: 3,
        title: "오빠닭 닭가슴살·볶음밥 최대 65% 할인",
        subTitle: "",
        type: "할인 이벤트",
        imagePath: "https://user-images.githubusercontent.com/46476398/177965239-ce84095a-9e35-4839-b851-7d7b2ea802e8.png",
        content: "",
        deadline: "22.07.14",
        status: "진행중",
    }, {
        eventId: 11,
        title: "교촌 닭가슴살·볶음밥 최대 61% 할인",
        subTitle: "",
        type: "할인 이벤트",
        imagePath: "https://user-images.githubusercontent.com/46476398/177965223-55ee573a-7fff-4af8-97bd-529f545918ea.png",
        content: "",
        deadline: "22.07.14",
        status: "종료",
    },
    {
        eventId: 12,
        title: "랭킹닭컴 X KB국민카드, 결재시 20% 할인",
        subTitle: "",
        type: "할인 이벤트",
        imagePath: "https://user-images.githubusercontent.com/46476398/177965235-8d8dfec1-97c5-4497-b4df-e50229098513.png",
        content: "",
        deadline: "22.07.14",
        status: "진행중",
    },
    {
        eventId: 13,
        title: "오빠닭 닭가슴살·볶음밥 최대 65% 할인",
        subTitle: "",
        type: "할인 이벤트",
        imagePath: "https://user-images.githubusercontent.com/46476398/177965239-ce84095a-9e35-4839-b851-7d7b2ea802e8.png",
        content: "",
        deadline: "22.07.14",
        status: "진행중",
    }, {
        eventId: 21,
        title: "교촌 닭가슴살·볶음밥 최대 61% 할인",
        subTitle: "",
        type: "할인 이벤트",
        imagePath: "https://user-images.githubusercontent.com/46476398/177965223-55ee573a-7fff-4af8-97bd-529f545918ea.png",
        content: "",
        deadline: "22.07.14",
        status: "종료",
    },
    {
        eventId: 22,
        title: "랭킹닭컴 X KB국민카드, 결재시 20% 할인",
        subTitle: "",
        type: "할인 이벤트",
        imagePath: "https://user-images.githubusercontent.com/46476398/177965235-8d8dfec1-97c5-4497-b4df-e50229098513.png",
        content: "",
        deadline: "22.07.14",
        status: "진행중",
    },
    {
        eventId: 23,
        title: "오빠닭 닭가슴살·볶음밥 최대 65% 할인",
        subTitle: "",
        type: "할인 이벤트",
        imagePath: "https://user-images.githubusercontent.com/46476398/177965239-ce84095a-9e35-4839-b851-7d7b2ea802e8.png",
        content: "",
        deadline: "22.07.14",
        status: "진행중",
    },
]

export const dummyETCResultList = [
    {
        title: "‘마이프로틴 할인정보’ 인스타그램",
        imagePath: "https://user-images.githubusercontent.com/79794580/177980376-d5483417-6bb8-4164-b12f-3d6773748f4c.jpg",
        url: "https://www.instagram.com/myprotein_alarm/",
    },
    {
        title: "‘마이프로틴 할인정보’ 페이스북",
        imagePath: "https://user-images.githubusercontent.com/79794580/177980428-02023ecc-d750-427b-8268-ddabf70ea9ce.jpg",
        url: "https://www.facebook.com/%EB%A7%88%EC%9D%B4%ED%94%84%EB%A1%9C%ED%8B%B4-%ED%95%A0%EC%9D%B8%EC%A0%95%EB%B3%B4-112365694813764",
    },
    {
        title: "‘단슐랭’ 유튜브",
        imagePath: "https://user-images.githubusercontent.com/79794580/177980419-2cc03612-6dcd-473f-a059-f7b7497c270f.jpg",
        url: "https://www.youtube.com/channel/UCoQw5My6QTmiX6XawgD9ejw/featured",
    },
    {
        title: "‘플랫폼 창업기’ 네이버 블로그",
        imagePath: "https://user-images.githubusercontent.com/79794580/177980425-c24fca27-fd5a-439a-9ad8-7dfe822c693c.jpg",
        url: "https://blog.naver.com/tisalron",
    },
]

export const dummyBannerList = [
    {
        mainBannerId: 0,
        thumbnailImagePath:
            'https://user-images.githubusercontent.com/46476398/180156245-8772524a-a4b6-40c8-91e9-fa453b8dc450.png',
    },
    {
        mainBannerId: 1,
        thumbnailImagePath:
            'https://user-images.githubusercontent.com/46476398/180154994-3f6dda45-b765-4be5-b39c-c17c48c59138.png',
    },
    {
        mainBannerId: 2,
        thumbnailImagePath:
            'https://user-images.githubusercontent.com/46476398/180156245-8772524a-a4b6-40c8-91e9-fa453b8dc450.png',
    },
    {
        mainBannerId: 3,
        thumbnailImagePath:
            'https://user-images.githubusercontent.com/46476398/180154994-3f6dda45-b765-4be5-b39c-c17c48c59138.png',
    },
    {
        mainBannerId: 4,
        thumbnailImagePath:
            'https://user-images.githubusercontent.com/46476398/180156245-8772524a-a4b6-40c8-91e9-fa453b8dc450.png',
    },
]

export const dummyDSBPickList = [
    {
        id: 1,
        title: "부드러운 닭가슴살",
        description: "입에서 살살 녹아요!",
        imagePath: "https://user-images.githubusercontent.com/79794580/180383084-76baec50-a7f5-438c-bd57-f9b6be398fe2.png",
    },
    {
        id: 2,
        title: "WPC vs WPI",
        description: "유당불내증 있으신가요?",
        imagePath: "https://user-images.githubusercontent.com/79794580/180383599-069686a2-4efc-4442-b888-3b6a7ec7590c.png",
    },
    {
        id: 3,
        title: "그릴드 닭가슴살 모음",
        description: "불맛이 느껴지실꺼에요!",
        imagePath: "https://user-images.githubusercontent.com/79794580/180383618-2440974c-28f4-437a-9e6b-f455f465ea54.png",
    },
    {
        id: 4,
        title: "단성비 샐러드 PICK",
        description: "풀때기로 포만감을!",
        imagePath: "https://user-images.githubusercontent.com/79794580/180383614-f0a41463-81cc-4dcd-93ff-78af004f2fc1.png",
    },
    {
        id: 5,
        title: "마시기 편한 보충제",
        description: "입에 찝찝함이 남지 않아요!",
        imagePath: "https://user-images.githubusercontent.com/79794580/180383616-177d721a-c74b-4fb7-bec4-c00163bccef6.png",
    },
]

export const dummyNutrientInfo = {
    perCapacity: "1개(100g)",
    nutrientList: [
        {
            name: "칼로리",
            imgPath: "https://user-images.githubusercontent.com/46476398/180648225-c3b8d35c-5544-48df-8e5c-664553a2483c.png",
            description: "120kcal",
        },
        {
            name: "탄수화물",
            imgPath: "https://user-images.githubusercontent.com/46476398/180648238-19682329-8645-487c-9d83-7628ef127e98.png",
            description: "10g",
        },
        {
            name: "단백질",
            imgPath: "https://user-images.githubusercontent.com/46476398/180648254-5162f3c3-24fb-4da9-932b-20fde70d98a5.png",
            description: "20g",
        },
        {
            name: "지방",
            imgPath: "https://user-images.githubusercontent.com/46476398/180648259-458ff364-236b-4a92-8204-357a2d0902c6.png",
            description: "20g",
        },
    ],
}

export const dummyIngredientInfo = {
    totalIngredientNum: 8,
    ingredientList: [
        {
            name: "식물성 원료",
            number: 2,
        },
        {
            name: "동물성 원료",
            number: 2,
        },
        {
            name: "첨가물",
            number: 2,
        },
        {
            name: "기능성 원료",
            number: 1,
        },
        {
            name: "기타",
            number: 1,
        },
    ],
    allergyList: [
        {
            name: "우유",
            imgPath: "https://user-images.githubusercontent.com/46476398/180648269-8e461db0-7002-47f2-89e0-24e8f227a418.png",
        },
        {
            name: "땅콩",
            imgPath: "https://user-images.githubusercontent.com/46476398/180648269-8e461db0-7002-47f2-89e0-24e8f227a418.png",
        },
        {
            name: "달걀",
            imgPath: "https://user-images.githubusercontent.com/46476398/180648269-8e461db0-7002-47f2-89e0-24e8f227a418.png",
        },
        {
            name: "밀",
            imgPath: "https://user-images.githubusercontent.com/46476398/180648269-8e461db0-7002-47f2-89e0-24e8f227a418.png",
        },
        {
            name: "냠냠",
            imgPath: "https://user-images.githubusercontent.com/46476398/180648269-8e461db0-7002-47f2-89e0-24e8f227a418.png",
        },
    ],
    sideEffectList: [
        {
            name: "불면증",
            imgPath: "https://user-images.githubusercontent.com/46476398/180648269-8e461db0-7002-47f2-89e0-24e8f227a418.png",
        },
        {
            name: "유당불내증",
            imgPath: "https://user-images.githubusercontent.com/46476398/180648269-8e461db0-7002-47f2-89e0-24e8f227a418.png",
        },
        {
            name: "신장 질환 주의",
            imgPath: "https://user-images.githubusercontent.com/46476398/180648269-8e461db0-7002-47f2-89e0-24e8f227a418.png",
        },
    ],
}

export const dummyReviewInfo = {
    totalReviewNum: 19,
    averageReviewRating: 4.2,
    ratingList: [
        10,
        3,
        2,
        1,
        3
    ],
    reviewList: [
        {
            reviewNo: 16,
            profileImgPath: "https://healthfriend.s3.ap-northeast-2.amazonaws.com/user/user_default.png",
            nickname: "정승욱",
            ages: "40대",
            gender: "여성",
            rating: 5.00,
            childProductNo: 557,
            flavor: "갈릭맛",
            flavorStr: "임시 맛",
            unit: "1개",
            capacityStr: "10팩",
            contentList: "",
            like: 4,
            isUserLike: true,
            isUserWrite: false,
            updated: "2022.01.29",
        },
        {
            reviewNo: 17,
            profileImgPath: "https://healthfriend.s3.ap-northeast-2.amazonaws.com/user/user_default.png",
            nickname: "피터현",
            ages: "30대",
            gender: "남성",
            rating: 4.00,
            childProductNo: 557,
            flavor: "갈릭맛",
            flavorStr: "임시 맛",
            unit: "1개",
            capacityStr: "10팩",
            contentList: "",
            like: 4,
            isUserLike: true,
            isUserWrite: false,
            updated: "2022.01.29",
        },
        {
            reviewNo: 18,
            profileImgPath: "https://healthfriend.s3.ap-northeast-2.amazonaws.com/user/user_default.png",
            nickname: "세상지배가루",
            ages: "30대",
            gender: "여성",
            rating: 1.00,
            childProductNo: 557,
            flavor: "갈릭맛",
            flavorStr: "임시 맛",
            unit: "1개",
            capacityStr: "10팩",
            contentList: "",
            like: 4,
            isUserLike: true,
            isUserWrite: false,
            updated: "2022.01.29",
        },
        {
            reviewNo: 19,
            profileImgPath: "https://healthfriend.s3.ap-northeast-2.amazonaws.com/user/user_default.png",
            nickname: "이쁜사람",
            ages: "20대",
            gender: "여성",
            rating: 2.00,
            childProductNo: 557,
            flavor: "갈릭맛",
            flavorStr: "임시 맛",
            unit: "1개",
            capacityStr: "10팩",
            contentList: "",
            like: 4,
            isUserLike: true,
            isUserWrite: false,
            updated: "2022.01.29",
        },
    ]
}

export const dummyReviewTagList = [
    {
        key: "맛",
        description: "해당 상품의 맛이 어떠셨는지 평가해주세요.",
        value: "",
        valueSelectionList: [
            "최악이에요",
            "별로에요",
            "보통이에요",
            "좋아요",
            "최고에요",
        ],
    },
    {
        key: "식감",
        description: "해당 상품의 식감이 어떠셨는지 평가해주세요.",
        value: "",
        valueSelectionList: [
            "질겨요",
            "적당해요",
            "부드러워요",
        ],
    },
    {
        key: "재구매 의사",
        description: "해당 제품을 다시 구매하실 의사가 있으신가요?",
        value: "",
        valueSelectionList: [
            "있어요",
            "없어요",
        ],
    },
]

export const dummyProductInfoForComparison = {
    comparisonTarget: {
        childProductId: 750,
        productSerialNumber: "146_750",
        parentProductName: "닭가슴살",
        parentProductBrand: "수지스",
        imagePath: "https://healthfriend.s3.ap-northeast-2.amazonaws.com/20220920T025558149Z_portvalue.png",
        flavorStr: "그릴드맛",
        capacityStr: "550g",
        repDistributorMapId: 2853,
        price: 11400,
        amount: 1,
        reviewTotalCount: 1,
        reviewAverageRating: 5,
        favoriteTotalCount: 1,
        nutrient: {
            protein: 22,
            carbohydrate: 8,
            fat: 2.2,
            sodium: 294
        },
    },
    productListForComparison: [
        {
            childProductId: 752,
            productSerialNumber: "146_752",
            parentProductName: "닭가슴살",
            parentProductBrand: "수지스",
            imagePath: "https://healthfriend.s3.ap-northeast-2.amazonaws.com/20220920T025614681Z_portvalue.png",
            flavorStr: "페퍼콘맛",
            capacityStr: "550g",
            repDistributorMapId: 2490,
            price: 12400,
            amount: 1,
            reviewTotalCount: 1,
            reviewAverageRating: 5,
            favoriteTotalCount: 0,
            nutrient: {
                calory: 140,
                protein: 22,
                carbohydrate: 8,
                fat: 2.2,
                sodium: 294
            },
        },
        {
            childProductId: 951,
            productSerialNumber: "201_951",
            parentProductName: "냉장 닭가슴살",
            parentProductBrand: "하림",
            imagePath: "https://healthfriend.s3.ap-northeast-2.amazonaws.com/20221007T002641336Z_portvalue.png",
            flavorStr: "오리지널맛",
            capacityStr: "110g",
            repDistributorMapId: 4252,
            price: 20000,
            amount: 10,
            reviewTotalCount: 0,
            reviewAverageRating: 0,
            favoriteTotalCount: 0,
            nutrient: {
                calory: 140,
                protein: 22,
                carbohydrate: 8,
                fat: 2.2,
                sodium: 294
            },
        },
        {
            childProductId: 1093,
            productSerialNumber: "260_1093",
            parentProductName: "수지스 그릴드 닭가슴살",
            parentProductBrand: "코스트코",
            imagePath: "https://healthfriend.s3.ap-northeast-2.amazonaws.com/20221027T060927693Z_portvalue.png",
            flavorStr: "그릴드맛",
            capacityStr: "1kg",
            repDistributorMapId: 4451,
            price: 18900,
            amount: 1,
            reviewTotalCount: 0,
            reviewAverageRating: 0,
            favoriteTotalCount: 0,
            nutrient: {
                calory: 140,
                protein: 22,
                carbohydrate: 8,
                fat: 2.2,
                sodium: 294
            },
        },
    ]
}